services:
  master:
    build:
       context: .
       dockerfile: Dockerfile
    image: crawlabteam/crawlab:0.6.3
    container_name: crawlab_master
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    env_file:
      - ../.env
    environment:
      TZ: ${TZ}
      CRAWLAB_NODE_MASTER: "Y"  # Y: master node
      CRAWLAB_MONGO_HOST: "mongo"  # mongo host address. In the docker compose network, directly refer to the service name
      CRAWLAB_MONGO_PORT: "27017"  # mongo port
      CRAWLAB_MONGO_DB: ${MONGO_DATABASE}  # mongo database
      CRAWLAB_MONGO_USERNAME: ${MONGO_USERNAME}  # mongo username
      CRAWLAB_MONGO_PASSWORD: ${MONGO_PASSWORD}  # mongo password
      CRAWLAB_MONGO_AUTHSOURCE: "admin"  # mongo auth source
    volumes:
      - "/opt/.crawlab/master:/root/.crawlab"  # persistent crawlab metadata
      - "/opt/crawlab/master:/data"  # persistent crawlab data

    ports:
      - "8080:8080"  # exposed api port
    depends_on:
      - mongo

  mongo:
    image: mongo:8.2.2
    restart: always
    container_name: mongodb
    env_file:
      - ../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}  # mongo username
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}  # mongo password
    volumes:
      - "/opt/.crawlab/master:/root/.crawlab"  # persistent crawlab metadata
      - "/opt/crawlab/mongo/data/db:/data/db"  # persistent mongo data
    ports:
      - "27017:27017"  # expose mongo port to host machine

 
